Feature/selling partner services
lincolnaleixo/ConquerAmz-API pull request #6
Opened 2021-06-18 00:20 UTC by geni94

## Users:
- CRUD actions
- DB write/read

## Authentication:
- JWT integration: decode/encode
- Bearer authentication in middleware

## Selling Partner actions
- some inventory and orders test calls

2021-06-18 22:30 UTC, lincolnaleixo requested changes
please check comments about the db string

2021-06-18 22:30 UTC, lincolnaleixo commented on db/db.mjs
>  const cloudUri = `mongodb+srv://eugenDb:${password}@cluster0.grdmy.mongodb.net/${dbName}?retryWrites=true&w=majority`;
better put the "eugenDb" as env as well

2021-06-18 22:30 UTC, lincolnaleixo commented on index.js
> +const cloudUri = `mongodb+srv://eugenDb:${process.env.DB_PASSWORD}@cluster0.grdmy.mongodb.net/${process.env.DB_NAME}?retryWrites=true&w=majority`;
same here (eugenDb)

2021-06-21 09:30 UTC, geni94 commented on index.js
> +const cloudUri = `mongodb+srv://eugenDb:${process.env.DB_PASSWORD}@cluster0.grdmy.mongodb.net/${process.env.DB_NAME}?retryWrites=true&w=majority`;
Fixed 1eadeac7dee79530909873c65efa1b4698ae3c72

2021-06-21 09:30 UTC, geni94 commented on db/db.mjs
>  const cloudUri = `mongodb+srv://eugenDb:${password}@cluster0.grdmy.mongodb.net/${dbName}?retryWrites=true&w=majority`;
fixed 1eadeac7dee79530909873c65efa1b4698ae3c72

2021-06-22 00:03 UTC, lincolnaleixo approved these changes

2021-06-22 00:03 UTC, merged